### PR TITLE
SPORTSHUB-219 mobile view for manage attendees and event drill down

### PR DESCRIPTION
**Pull request by owya490**
## Why was your change needed?

Please detail here why you did the change you did.

## What was Changed?

Please detail here what were the main changes you made.

## Any extra notes for reviewers to know?

Write any extra notes you may have for the PR.
This may include specific code paths that need extra scrutiny, or how to review a specific portion of code.

### CODE REVIEW

**Comment by Edwin-Ni** [comment]
IMG_7634

IMG_7635

1. Adjusting price causes things to be misaligned
2. Success notification in awkward spot covering navbar and doesn't auto dismiss, probably better to be up higher and not covering any functionality

Below is a timer for auto dismiss.

```
  useEffect(() => {
    let timer: number | undefined;

    if (showLoginSuccess) {
      timer = window.setTimeout(() => {
        setShowLoginSuccess(false);
      }, 3000);
    }

    return () => {
      if (timer) {
        clearTimeout(timer);
      }
    };


```

**Comment by owya490** [comment]
@41dan, sure i can add a bit more padding, but overall phone view should span edge to edge and take up the entire width.

As for the email overflow, yes at some widths it wil happen, but unfortunately i dont think its practical to code for every screen size to the pixel. In most phone views i believe when i checked it was fine. 

I will try make it overflow hidden and u have to swipe to see it all, but thats about as good as i can make it. 

Anyone who puts in a massive email will always have this problem sad.

**Comment by owya490** [comment]
@Edwin-Ni 

good points, i think the misalign, i will need to investigate later, let me raise it as a card.

i will make the notification time out and move it higher. I want to PR in asap before the syrio event. Thanks

**Comment by owya490** [comment]
@Edwin-Ni here is the misalignment issue: https://owenyang.atlassian.net/browse/SPORTSHUB-256

**Review by 41dan — APPROVED** [review]
lgtm

**Pull request merged**
